main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
]

projects/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from . import views
from .views import projectListView, SubprojectListView, SubprojectReleaseListView, RootDetailView, SubprojectReleasePackageListView  , packageListView                                                                                                



urlpatterns = [
    path('', lambda request: redirect('home/root', permanent=False)),
    path("home/<slug:slug>", RootDetailView.as_view()),
    path("packages", packageListView.as_view()),
    path("projects/", projectListView.as_view()),
    path("project/<pk>", SubprojectListView.as_view()),
    path("subproject/<pk>", SubprojectReleaseListView.as_view()),
    path("releases/<slug:slug>", SubprojectReleasePackageListView.as_view()),
]

sclbuilder/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('projects.urls')),
    path('admin/', admin.site.urls),
]

projects/models.py
from django.db import models
from datetime import date, datetime
from django.urls import reverse
from django.db.models.fields import BLANK_CHOICE_DASH
#from django.views.generic.list import T


class rootdetail(models.Model):
    slug = models.SlugField(null=True)
    headline = models.CharField(max_length=255, default="Ajax opensource turnkey projects")
    footer = models.CharField(max_length=255, default=" 2021 Ajax")
    body = models.CharField(max_length=8192, blank=True, null=True)
    projects = models.BigIntegerField(default=0)
    projectsbuild = models.BigIntegerField(default=0)
    packages = models.BigIntegerField(default=0)
    packagesbuild = models.BigIntegerField(default=0)
    contactname = models.CharField(max_length=64, default="John Doe")
    contactmail = models.CharField(max_length=64, default="JohnDoe@mail.ajax.void")
    contactorg = models.CharField(max_length=128, default="Ajax corp.")
    logo = models.URLField(default="http://repos.pip2scl.dk/logos/sclbuilder.png")
    def __str__(self):
      return self.slug




class project2(models.Model):
    thismoment = datetime.now
    STATUSES = (
        ('Initial', 'Initial stated - Work to be done'),
        ('Building', 'Building in progress'),
        ('Completed', 'Build completed succesfully'),
        ('Failed', 'Build failed and interaction'),
    )
    slug = models.SlugField(null=True) # new
    projectname = models.CharField(max_length=50, unique=True)
    projectname = models.CharField(max_length=50, unique=True)
    projectversion = models.CharField(max_length=50, default="001")
    projectdescription = models.CharField(max_length=256, default="This is the project description")
    projectstatus = models.CharField( max_length=256, choices=STATUSES, default="Initial")
    projectcreated = models.DateField(default=thismoment)
    projectdeployed = models.DateField(blank=True, null=True)
    projecturl = models.URLField(blank=True, default="http://repos.pip2scl.dk/PROJECTS/README.md", null=True)
    projectlogourl = models.ForeignKey('projects.sclbuilderlogos', to_field='sclbuilderlogoname', on_delete=models.CASCADE, default="default", null=True)
    totalsubprojects = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    totalsubprojectsbuilding = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    totalsubprojectsbuild = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    totalsubprojectsfailed = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    def __str__(self):
        return self.projectname
    
    

class project(models.Model):
    thismoment = datetime.now
    STATUSES = (
        ('Initial', 'Initial stated - Work to be done'),
        ('Building', 'Building in progress'),
        ('Completed', 'Build completed succesfully'),
        ('Failed', 'Build failed and interaction'),
    )
    slug = models.SlugField(null=True) # new
    projectname = models.CharField(max_length=50, unique=True)
    projectversion = models.CharField(max_length=50, default="001")
    projectdescription = models.CharField(max_length=256, default="This is the project description")
    projectstatus = models.CharField( max_length=256, choices=STATUSES, default="Initial")
    projectcreated = models.DateField(default=thismoment)
    projectdeployed = models.DateField(blank=True, null=True)
    projecturl = models.URLField(blank=True, default="http://repos.pip2scl.dk/PROJECTS/README.md", null=True)
    projectlogourl = models.ForeignKey('projects.sclbuilderlogos', to_field='sclbuilderlogoname', on_delete=models.CASCADE, default="default", null=True)
    totalsubprojects = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    totalsubprojectsbuilding = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    totalsubprojectsbuild = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    totalsubprojectsfailed = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    def __str__(self):
        return self.projectname
    
    


class subproject(models.Model):
    thismoment = datetime.now
    STATUSES = (
        ('Initial', 'Initial stated - Work to be done'),
        ('Building', 'Building in progress'),
        ('Completed', 'Build completed succesfully'),
        ('Failed', 'Build failed and interaction'),
    )
    projectname = models.ForeignKey( 'projects.project', to_field='projectname', on_delete=models.CASCADE)
    subprojectname = models.CharField(max_length=50, unique=True)
    subprojectversion = models.CharField(max_length=50, default="001")
    subprojectdescription = models.CharField(max_length=256, default="This is the description of the sub project" )
    subprojectstatus = models.CharField( max_length=256, choices=STATUSES, default="Initial")
    subprojectcreated = models.DateField(default=thismoment)
    subprojectdeployed = models.DateField(blank=True, null=True)
    subprojecturl = models.URLField(blank=True, null=True)
    subprojectlogourl = models.ForeignKey('projects.sclbuilderlogos', to_field='sclbuilderlogoname', on_delete=models.CASCADE, default="default", null=True)
    subprojectreleases = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    subprojectreleasesbuilding = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    subprojectreleasesbuild = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    subprojectreleasesfailed = models.PositiveSmallIntegerField(default=0, null=True)
    slug = models.SlugField(null=True, default=projectname)
    def __str__(self):
        return self.subprojectname



class subprojectrelease(models.Model):
    thismoment = datetime.now
    STATUSES = (
        ('Initial', 'Initial stated - Work to be done'),
        ('Building', 'Building in progress'),
        ('Completed', 'Build completed succesfully'),
        ('Failed', 'Build failed and interaction'),
    )
    subprojectname = models.ForeignKey( 'projects.subproject', to_field='subprojectname', on_delete=models.CASCADE)
    releasename = models.CharField(max_length=50, unique=True)
    releaseversion = models.CharField(max_length=50)
    releasebuild = models.CharField(max_length=50, default="001")
    releasedescription = models.CharField(max_length=256, default="This is the description of the releas")
    releasestatus = models.CharField( max_length=256, choices=STATUSES, default="Initial")
    releasecreated = models.DateField(default=thismoment)
    releasedeployed = models.DateField(blank=True, null=True)
    releaserequirementurl = models.URLField(blank=True, null=True)
    releaserequirements = models.PositiveSmallIntegerField(default=0, blank=True, null=True)
    releaserequirementsbuilding = models.PositiveSmallIntegerField(default=0, blank=True, null=True)
    releaserequirementsbuild = models.PositiveSmallIntegerField(default=0, blank=True, null=True)
    releaserequirementsfailed = models.PositiveSmallIntegerField(default=0, blank=True, null=True)
    slug = models.SlugField(null=True, default=subprojectname)

    def __str__(self):
        specificrelease = "%s:%s/%s" % (self.subprojectname, self.releaseversion , self.releasename)
        return specificrelease


class package(models.Model):
    thismoment = datetime.now
    # Countries Choices
    STATUSES = (
        ('Initial', 'Initial stated - Work to be done'),
        ('Building', 'Building in progress'),
        ('Completed', 'Build completed succesfully'),
        ('Failed', 'Build failed and interaction'),
    )
    PYTHONVERSIONS = (
        ('3.9', 'python3.9'),
        ('3.8', 'python3.8'),
        ('2', 'python2')
    )
    slug = models.SlugField(null=True, unique=True)
    packagename = models.CharField(max_length=50)
    packageversion = models.CharField(max_length=50)
    packagestatus = models.CharField(max_length=50, choices=STATUSES, default="Initial")
    packagestatusurl = models.URLField(blank=True, null=True)
    packagecreated = models.DateField(blank=True, null=True)
    packagedescription = models.CharField(max_length=256, default="This is the package description", blank=True, null=True)
    packagepythonversion = models.CharField(max_length=12, choices=PYTHONVERSIONS, default="3.8", blank=True, null=True)

    packagesourcefileurlorg = models.URLField(blank=True, null=True)
    packagesourcefileurl = models.URLField(blank=True, null=True)
    packagesourcefilestatus = models.CharField(max_length=50, choices=STATUSES, default="Initial", blank=True, null=True)
    packagepackagesourcefileurlorgmeta = models.CharField(max_length=256, choices=STATUSES, default="Initial", blank=True, null=True)
    packagesourcefilecreated = models.DateField(blank=True, null=True)
    packagesourcefileverified = models.DateField(blank=True, null=True)
    packagesourcefiledeployed = models.DateField(blank=True, null=True)

    packageorgspecfileurl = models.URLField(blank=True, null=True)
    packageorgspecfilestatus = models.CharField(max_length=50, choices=STATUSES, default="Initial", blank=True, null=True)
    packageorgspecfilecreated = models.DateField(blank=True, null=True)
    packageorgspecfileverified = models.DateField(blank=True, null=True)
    packageorgspecfiledeployed = models.DateField(blank=True, null=True)
    
    packagespecfileurl = models.URLField(blank=True, null=True)
    packagespecfilestatus = models.CharField(max_length=50, choices=STATUSES, default="Initial", blank=True, null=True)
    packagespecfilecreated = models.DateField(blank=True, null=True)
    packagespecfileverified = models.DateField(blank=True, null=True)
    packagespecfiledeployed = models.DateField(blank=True, null=True)
    
    packagerpmfilesurl = models.URLField(blank=True, null=True)
    packagerpmfilestatus = models.CharField(max_length=50, choices=STATUSES, default="Initial", blank=True, null=True)
    packagerpmfilecreated = models.DateField(blank=True, null=True)

projects/forms.py
from django import forms

class projectForm(forms.Form):
    project_name = forms.CharField(label='project name', max_length=100)

projects/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponseForbidden
from django.http import Http404

from .models import rootdetail
from .models import project
from .models import subproject
from .models import subprojectrelease

from .models import package
from .models import requirement
from .models import packagetweak
from .models import packagetweakrelation

class projectListView(ListView):
    model = project 
    template_name = 'projects.html'

class SubprojectListView(ListView):
    # specify the model for create view
    model = subproject 
    template_name = 'Subprojects.html'


class SubprojectReleaseListView(ListView):
    # specify the model for create view
    model = subprojectrelease
    template_name = 'SubprojectReleases.html'

class SubprojectReleasePackageListView(ListView):
    # specify the model for create view
    model =  requirement
    template_name = 'SubprojectReleasePackages.html'


class RootDetailView(DetailView):
    model = rootdetail
    template_name = 'rootdetailview.html'


class packageListView(ListView):
    # specify the model for create view
    model = package 
    template_name = 'packages.html'
    ordering = ['packagesclrpmfilestatus']

projects/templates/CreateProject.html
<!DOCTYPE html>
<html>
   <head>
   </head>
    <body onload="document.createElement('form').submit.call(document.getElementById('myForm'))">
        <form id="myForm" name="myForm" action="http://builder.pip2scl.dk/dG9rZW50b2tlbnRva2VudG9rZW50b2tlbnRva2VudG9rZW4K/showproject" method="POST">
            {% csrf_token %} 
            {{ form.as_p }}
            <input type=hidden name="projectname" id="id_projectname" value="autocreateproject"/> 
        <input type="submit" value="save"> 
    </form>
   </body>
</html>

projects/templates/DeleteProject.html
<!DOCTYPE html>
<html>
   <head>
   </head>
   <body>

<h1>project Delete</h1>


<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>




 </body>
</html>

projects/templates/SubprojectReleasePackages.html
Hello

projects/templates/SubprojectReleases.html
<!doctype html>
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'css/projectlayout.css' %}"/>
    <title>Miracle opensource projects</title>
        <head>
        </head>
        <body>
            <div class="wrapper">
                <div class="box header">
                    <h2>Miracle opensource turnkey projects</h2>
                </div>
                <div class="box sidebar">
                    <a href="/">Home</a><br>
                    <a href="/projects">Projects</a><br>
                    <a href="/packages">Packages</a><br>  
                </div>
                <div class="box content">



                <table border="1">
                  <tr>
                    <th width="5%">Name</th>
                    <th width="2%">Version</th>
                    <th>Description</th>
                    <th width="5%">Releases</th>
                    <th width="5%">Building</th>
                    <th width="5%">Ready</th>
                    <th Width="5%">Failed</th>
                    <th width="2%"></th>
                </tr>
                {% for subprojectrelease in object_list %}
                <tr>
                    <td>{{ subprojectrelease.releasename }}</td>
                    <td>{{ subprojectrelease.releaseversion }}</td>
                    <td>{{ subprojectrelease.releasedescription }}</td>
                    <td align ="center">{{ subprojectrelease.releaserequirements }} </td>
                    <td align ="center">{{ subprojectrelease.releaserequirementsbuilding }}</td>
                    <td align ="center">{{ subprojectrelease.releaserequirementsbuild }}</td>
                    <td align ="center">{{ subprojectrelease.releaserequirementsfailed }}</td>
                        <td><a href="http://builder.pip2scl.dk/subproject/{{ subproject.subprojectname }}">
                            <img align="left" src="http://repos.pip2scl.dk/logos/crayarrow.png" alt="Go" width="32" height="32">
                        </a>
                    </td>
                </tr>
                {% empty %}
                   <a href="http://builder.pip2scl.dk/createnewsubproject" >
                   Create new subproject
                   </a>
                {% endfor %}
                </table>

            </div>
            <div class="box footer">
                <center>2021 Miracle opensource projects 2021</center>
                <meta http-equiv="refresh" content="10"> 
            </div>
        </div>
    </body>
</html>

projects/templates/Subprojects.html
<!doctype html>
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'css/projectlayout.css' %}"/>
    <title>Miracle opensource projects</title>
        <head>
        </head>
        <body>
            <div class="wrapper">
                <div class="box header">
                    <h2>Miracle opensource turnkey projects</h2>
                </div>
                <div class="box sidebar">
                    <a href="/">Home</a><br>
                    <a href="/projects">Projects</a><br>
                    <a href="/packages">Packages</a><br>
                </div>
                <div class="box content">



                <table border="1">
                  <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Version</th>
                    <th>Description</th>
                    <th>Releases</th>s</th>
                    <th>Building</th>
                    <th>Ready</th>
                    <th>Failed</th>
                    <th></th>
                </tr>
                {% for subproject in object_list %}
                <tr>
                    <td><img align="left"  src="{{ subproject.subprojectlogourl }}" alt="Logo" width="64" height="64"></td>
                    <td>{{ subproject.subprojectname }}</td>
                    <td>{{ subproject.subprojectversion }}</td>
                    <td>{{ subproject.subprojectdescription }}</td>
                    <td align ="center">{{ subproject.subprojectreleases  }}</td>
                    <td align ="center">{{ subproject.subprojectreleasesbuilding }}</td>
                    <td align ="center">{{ subproject.subprojectreleasesbuild }}</td>
                    <td align ="center">{{ subproject.subprojectreleasesfailed }}</td>
                    <td><a href="http://builder.pip2scl.dk/subproject/{{ subproject.subprojectname }}"><img align="left" src="http://repos.pip2scl.dk/logos/crayarrow.png" alt="Go" width="32" height="32"></td>
                </tr>
                {% empty %}
                   <a href="http://builder.pip2scl.dk/createnewsubproject" >
                   Create new subproject
                   </a>
                {% endfor %}
                </table>

            </div>
            <div class="box footer">
                <center>2021 Miracle opensource projects 2021</center>
                <meta http-equiv="refresh" content="10"> 
            </div>
        </div>
    </body>
</html>

projects/templates/packages.html
<!doctype html>
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'css/packagelayout.css' %}"/>
    <title>Miracle opensource packages</title>
        <head>
            <style>
                #customers {
                  font-family: Arial, Helvetica, sans-serif;
                  border-collapse: collapse;
                  width: 80%;
                  border: "1";
                }
                
                #customers td, #customers th {
                  border: 1px solid #ddd;
                  padding: 8px;
                  border-color: #85a4ab;
                }
                
                #customers tr:hover {background-color: #ddd;}
                
                #customers th {
                  padding-top: 12px;
                  padding-bottom: 12px;
                  text-align: left;
                  border-color: #85a4ab;
                }
                </style>
        </head>
        <body>
            <div class="wrapper">
                <div class="box header">
                    <h2>Miracle opensource python packages</h2>
                </div>
                <div class="box sidebar">
                    <a href="/">Home</a><br>
                    <a href="/projects">Projects</a><br>
                    <a href="/packages">Packages</a><br>
                </div>
                <div class="box content">

               <table id="buildstatus">
                  <tr>
                     <th width="2%"></th>
                     <th>Name</th>
                     <th width="12%">Version</th>
                     <th width="8%">Status</th>
                     <th width="8%">Source</th>
                     <th width="8%">Spec</th>
                     <th width="8%">RPM</th>
                     <th width="8%">SCL</th>
                     <th width="2%"></th>
                  </tr>
                {% for package in object_list.reverse %}
                <tr>
                    <td>{{ package.packagetli }}</td>
                    <td>{{ package.packagename }}</td>
                    <td>{{ package.packageversion }}</td>
                    <td class="{{ package.packagestatus }}">{{ package.packagestatus }}</td> <!-- status-->
                    <td class="{{ package.packagesourcefilestatus }}">{{ package.packagesourcefilestatus  }}</td><!---->
                    <td class="{{ package.packageorgspecfilestatus}}">{{ package.packageorgspecfilestatus  }}</td><!---->
                    <td class="{{ package.packagerpmfilestatus }}">{{ package.packagerpmfilestatus  }}</td><!---->
                    <td class="{{ package.packagesclrpmfilestatus }}">{{ package.packagesclrpmfilestatus  }}</td><!---->
                    <td><a href="http://builder.pip2scl.dk/package/{{ package.packagename }}"><img align="left" src="http://repos.pip2scl.dk/logos/crayarrow.png" alt="Go" width="32" height="32"></td>
                </tr>
                {% empty %}
                <b> Content ready to be deployed</b> <!--if  it emty-->
                {% endfor %}
                </table>
                </div>
                <div class="box footer">
                    <center>2021 Miracle opensource packages 2021 </center>
                    <meta http-equiv="refresh" content="10"> 
                </div>
            </div>
          </body>
</html>

projects/templates/projects.html
<!doctype html>
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'css/projectlayout.css' %}"/>
    <title>Miracle opensource projects</title>
        <head>
        </head>
        <body>
            <div class="wrapper">
                <div class="box header">
                    <h2>Miracle opensource turnkey projects</h2>
                </div>
                <div class="box sidebar">
                    <a href="/">Home</a><br>
                    <a href="/projects">Projects</a><br>
                    <a href="/packages">Packages</a><br>
                </div>
                <div class="box content">

               <table border="1" width="80%">
                   <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Sub-projects</th>
                    <th>Building</th>
                    <th>Ready</th>
                    <th>Failed</th>
                    <th></th>
                </tr>
                {% for project in object_list %}
                <tr>
                    <td><img align="left"  src="{{ project.projectlogourl }}" alt="Logo" width="64" height="64"></td>
                    <td>{{ project.projectname }}</td>
                    <td>{{ project.projectdescription }}</td>
                    <td align ="center">{{ project.totalsubprojects  }}</td>
                    <td align ="center">{{ project.totalsubprojectsbuilding }}</td>
                    <td align ="center">{{ project.totalsubprojectsbuild }}</td>
                    <td align ="center">{{ project.totalsubprojectsfailed }}</td>
                    <td><a href="http://builder.pip2scl.dk/project/{{ project.projectname }}"><img align="left" src="http://repos.pip2scl.dk/logos/crayarrow.png" alt="Go" width="32" height="32"></td>
                </tr>
                {% empty %}
                <b> Content ready to be deployed</b>
                {% endfor %}
                </table>
                </div>
                <div class="box footer">
                    2021 Miracle opensource projects 2021
                    <meta http-equiv="refresh" content="10"> 
                </div>
            </div>
        </body>
</html>

projects/templates/projects2.html
<!doctype html>
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'css/projectlayout.css' %}"/>
    <title>Miracle opensource projects</title>
        <head>
        </head>
        <body>
            <div class="wrapper">
                <div class="box header">
                    <h2>Miracle opensource turnkey projects</h2>
                </div>
                <div class="box sidebar">
                    <a href="/">Home</a><br>
                    <a href="/projects">Projects</a><br>
                    <a href="/packages">Packages</a><br>
                </div>
                <div class="box content">

               <table border="1" width="80%">
                   <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Sub-projects</th>
                    <th>Building</th>
                    <th>Ready</th>
                    <th>Failed</th>
                    <th></th>
                </tr>
                {% for project in object_list %}
                <tr>
                    <td><img align="left"  src="{{ project.projectlogourl }}" alt="Logo" width="64" height="64"></td>
                    <td>{{ project.projectname }}</td>
                    <td>{{ project.projectdescription }}</td>
                    <td align ="center">{{ project.totalsubprojects  }}</td>
                    <td align ="center">{{ project.totalsubprojectsbuilding }}</td>
                    <td align ="center">{{ project.totalsubprojectsbuild }}</td>
                    <td align ="center">{{ project.totalsubprojectsfailed }}</td>
                    <td><a href="http://builder.pip2scl.dk/project/{{ project.projectname }}"><img align="left" src="http://repos.pip2scl.dk/logos/crayarrow.png" alt="Go" width="32" height="32"></td>
                </tr>
                {% empty %}
                <b> Content ready to be deployed</b>
                {% endfor %}
                </table>
                </div>
                <div class="box footer">
                    2021 Miracle opensource projects 2021
                    <meta http-equiv="refresh" content="10"> 
                </div>
            </div>
        </body>
</html>

projects/templates/rootdetailview.html
<!doctype html>
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'css/projectlayout.css' %}"/>
    <title>{{ object.headline }}</title>
        <head>
        </head>
        <body>
            <div class="wrapper">
                <div class="box header">
                    <h2>{{ object.headline }}</h2>
                </div>
                <div class="box sidebar">
                    <a href="/">Home</a><br>
                    <a href="/projects">Projects ({{ object.projects }})</a><br>
                    <a href="/packages">Packages ({{ object.packages }})</a><br>
                </div>
                <div class="box content">
                    Projects : {{ object.projects }}
                    Packages : {{ object.packages }}
                </div>
                <div class="box footer">
                    {{ object.footer }} 
                    <meta http-equiv="refresh" content="10"> 
                </div>
            </div>
        </body>
</html>